export { HomePage } from "./homePage/HomePage"
export {AboutAcademyPage} from "./aboutAcademyPage/AboutAcademyPage"
export {GuidePage} from "./guidePage/GuidePage"
export {EducationPage} from "./educationPage/EducationPage"
export {SciencePage } from "./sciencePage/SciencePage"
export {ActivityPage} from "./activityPage/ActivityPage"
export {StudentsPage} from "./studentsPage/StudentsPage"
export {ApplicantsPage} from "./applicantsPage/ApplicantsPage"