export { Footer } from "./footer/Footer"
export { Header } from "./header/Header"
export {ActivStudents} from "./studentsSection/activStudents/ActivStudents"
export { ParlamentStudents} from "./studentsSection/parlamentStudents/ParlamentStudents"
export {StudentsHostel} from "./studentsSection/studentsHostel/StudentsHostel"
export {StudentsLife} from "./studentsSection/studentsLife/StudentsLife" 
export {Academy} from "./scienceSection/academiccouncil/Academy"
export {ScienceCenter} from "./scienceSection/sciencecenter/ScienceCenter"
export {Scientific} from "./scienceSection/scientificjournals/Scientific"
export { Cpo } from "./educationSection/cpo/Cpo"
export {ActivetyBaner} from "./activetySection/activetyBaner/ActivetyBaner"
export {Rector} from "./guideSection/rector/Rector"
export {Departments} from "./guideSection/departments/Departments"
export {Vacancies} from "./guideSection/vacancies/Vacancies"