export { Footer } from "./footer/Footer"
export { Header } from "./header/Header"
export { ActivStudents } from "./studentsSection/activStudents/ActivStudents"
export { ParlamentStudents } from "./studentsSection/parlamentStudents/ParlamentStudents"
export { StudentsHostel } from "./studentsSection/studentsHostel/StudentsHostel"
export { StudentsLife } from "./studentsSection/studentsLife/StudentsLife"
export { Academy } from "./scienceSection/academiccouncil/Academy"
export { ScienceCenter } from "./scienceSection/sciencecenter/ScienceCenter"
export { Scientific } from "./scienceSection/scientificjournals/Scientific"
export { Cpo } from "./educationSection/cpo/Cpo"
export { ActivetyBaner } from "./activetySection/activetyBaner/ActivetyBaner"
export { Rector } from "./guideSection/rector/Rector"
export { Departments } from "./guideSection/departments/Departments"
export { Vacancies } from "./guideSection/vacancies/Vacancies"

export { AboutCarousel } from "./aboutSection/aboutCarousel/AboutCarousel"
export { AboutDocument } from "./aboutSection/aboutDocument/AboutDocument"
export { AboutTexts } from "./aboutSection/aboutTexts/AboutTexts"
export { AboutNavigate } from "./aboutSection/aboutNavigate/AboutNavigate"

export { HomeBaaner } from "./homeSection/homeBanner/HomeBanner"
export { HomeNews } from "./homeSection/homeNews/HomeNews"
export { HomeStepen } from "./homeSection/homeStepen/HomeStepen"
export { HomeEvents } from "./homeSection/homeEvents/HomeEvents"
export { HomeJurnal } from "./homeSection/homeJurnal/HomeJurnal"
export { HomeJurnalComp } from "./homeSection/homeJurnal/HomeJurnalComp"
export { HomeJurnalVuz } from "./homeSection/homeJurnalVuz/HomeJurnalVuz"
export { JurnalVuzSl } from "./homeSection/homeJurnalVuz/JurnalVuzSl"
export { LinkSlider } from "./homeSection/sliderlinks/LinkSlider"
export { SliderHome } from "./homeSection/homeSlider/SliderHome"

export { EnrollAcademy } from './applicantsSection/enrollAcademy/EnrollAcademy';
export { AdmissionCommittee } from './applicantsSection/admissionCommittee/AdmissionCommittee';

export { GalleryBanner } from "./gallerySection/galleryBanner/GalleryBanner"
export { GalleryImg } from "./gallerySection/galleryImg/GalleryImg"