export {Header} from "./header/Header"
export {Footer} from "./footer/Footer"  
export {HomeBaaner} from "./homeSection/homeBanner/HomeBanner"
export {HomeNews} from "./homeSection/homeNews/HomeNews"
export {HomeStepen} from "./homeSection/homeStepen/HomeStepen"
export {HomeEvents} from "./homeSection/homeEvents/HomeEvents"
export {HomeJurnal} from "./homeSection/homeJurnal/HomeJurnal"
export {HomeJurnalComp} from "./homeSection/homeJurnal/HomeJurnalComp"